name = "capyops"
compatibility_date = "2024-03-01"
pages_build_output_dir = "dist"

# Aqui declaramos as variáveis de ambiente (deixe os valores sensíveis vazios aqui, 
# eles devem ser preenchidos no painel web do Cloudflare por segurança).
[vars]
MELI_API_URL = "https://api.mercadolibre.com"
# MELI_APP_ID = "preencher no painel"
# MELI_CLIENT_SECRET = "preencher no painel"
# MELI_REDIRECT_URI = "preencher no painel"
# SUPABASE_URL = "preencher no painel"
# SUPABASE_SERVICE_ROLE_KEY = "preencher no painel"
